// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    [Migration("20221217143649_sab1")]
    partial class sab1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3021),
                            Floor = 1,
                            Letter = "A",
                            Name = "1-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3055),
                            Floor = 1,
                            Letter = "B",
                            Name = "1-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3058),
                            Floor = 1,
                            Letter = "C",
                            Name = "1-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3060),
                            Floor = 2,
                            Letter = "A",
                            Name = "2-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3066),
                            Floor = 2,
                            Letter = "B",
                            Name = "2-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3068),
                            Floor = 2,
                            Letter = "C",
                            Name = "2-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3070),
                            Floor = 2,
                            Letter = "D",
                            Name = "2-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3073),
                            Floor = 2,
                            Letter = "E",
                            Name = "2-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3076),
                            Floor = 3,
                            Letter = "A",
                            Name = "3-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3078),
                            Floor = 3,
                            Letter = "B",
                            Name = "3-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3079),
                            Floor = 3,
                            Letter = "C",
                            Name = "3-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3081),
                            Floor = 3,
                            Letter = "D",
                            Name = "3-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3083),
                            Floor = 3,
                            Letter = "E",
                            Name = "3-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3085),
                            Floor = 4,
                            Letter = "A",
                            Name = "4-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3088),
                            Floor = 4,
                            Letter = "B",
                            Name = "4-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3090),
                            Floor = 4,
                            Letter = "C",
                            Name = "4-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3092),
                            Floor = 4,
                            Letter = "D",
                            Name = "4-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3094),
                            Floor = 4,
                            Letter = "E",
                            Name = "4-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3096),
                            Floor = 5,
                            Letter = "A",
                            Name = "5-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3097),
                            Floor = 5,
                            Letter = "B",
                            Name = "5-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3099),
                            Floor = 5,
                            Letter = "C",
                            Name = "5-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3101),
                            Floor = 5,
                            Letter = "D",
                            Name = "5-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3103),
                            Floor = 5,
                            Letter = "E",
                            Name = "5-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3105),
                            Floor = 6,
                            Letter = "A",
                            Name = "6-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3107),
                            Floor = 6,
                            Letter = "B",
                            Name = "6-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3109),
                            Floor = 6,
                            Letter = "C",
                            Name = "6-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3111),
                            Floor = 6,
                            Letter = "D",
                            Name = "6-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3112),
                            Floor = 6,
                            Letter = "E",
                            Name = "28-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3115),
                            Floor = 7,
                            Letter = "A",
                            Name = "7-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3117),
                            Floor = 7,
                            Letter = "B",
                            Name = "7-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3119),
                            Floor = 7,
                            Letter = "C",
                            Name = "7-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3121),
                            Floor = 7,
                            Letter = "D",
                            Name = "7-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3123),
                            Floor = 7,
                            Letter = "E",
                            Name = "33-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3125),
                            Floor = 8,
                            Letter = "A",
                            Name = "8-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3126),
                            Floor = 8,
                            Letter = "B",
                            Name = "8-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3128),
                            Floor = 8,
                            Letter = "C",
                            Name = "8-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3130),
                            Floor = 8,
                            Letter = "D",
                            Name = "8-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3132),
                            Floor = 8,
                            Letter = "E",
                            Name = "8-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3134),
                            Floor = 9,
                            Letter = "A",
                            Name = "9-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3136),
                            Floor = 9,
                            Letter = "B",
                            Name = "9-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3138),
                            Floor = 9,
                            Letter = "C",
                            Name = "9-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3139),
                            Floor = 9,
                            Letter = "D",
                            Name = "9-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3141),
                            Floor = 9,
                            Letter = "E",
                            Name = "9-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3143),
                            Floor = 10,
                            Letter = "A",
                            Name = "10-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3145),
                            Floor = 10,
                            Letter = "B",
                            Name = "10-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3147),
                            Floor = 10,
                            Letter = "C",
                            Name = "10-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3191),
                            Floor = 10,
                            Letter = "D",
                            Name = "10-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3194),
                            Floor = 10,
                            Letter = "E",
                            Name = "10-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3196),
                            Floor = 11,
                            Letter = "A",
                            Name = "11-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3199),
                            Floor = 11,
                            Letter = "B",
                            Name = "11-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3201),
                            Floor = 11,
                            Letter = "C",
                            Name = "11-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3203),
                            Floor = 11,
                            Letter = "D",
                            Name = "11-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 907, DateTimeKind.Local).AddTicks(3205),
                            Floor = 11,
                            Letter = "E",
                            Name = "11-E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte[]>("Document")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpenseName = "Artículos de limpieza"
                        },
                        new
                        {
                            Id = 2,
                            ExpenseName = "Caja de Seguro Social"
                        },
                        new
                        {
                            Id = 3,
                            ExpenseName = "Caja menuda"
                        },
                        new
                        {
                            Id = 4,
                            ExpenseName = "Cargos bancarios"
                        },
                        new
                        {
                            Id = 5,
                            ExpenseName = "Cerrajería"
                        },
                        new
                        {
                            Id = 6,
                            ExpenseName = "Conserje"
                        },
                        new
                        {
                            Id = 7,
                            ExpenseName = "Devolución de reserva"
                        },
                        new
                        {
                            Id = 8,
                            ExpenseName = "Fotocopias"
                        },
                        new
                        {
                            Id = 9,
                            ExpenseName = "Fumigación"
                        },
                        new
                        {
                            Id = 10,
                            ExpenseName = "Gastos legales"
                        },
                        new
                        {
                            Id = 11,
                            ExpenseName = "Mantenimiento de A/A."
                        },
                        new
                        {
                            Id = 12,
                            ExpenseName = "Mantenimiento de ascensores"
                        },
                        new
                        {
                            Id = 13,
                            ExpenseName = "Mantenimiento de bomba de agua"
                        },
                        new
                        {
                            Id = 14,
                            ExpenseName = "Mantenimiento de planta eléctrica"
                        },
                        new
                        {
                            Id = 15,
                            ExpenseName = "Mantenimiento de puertas mecánicas"
                        },
                        new
                        {
                            Id = 16,
                            ExpenseName = "Portería"
                        },
                        new
                        {
                            Id = 17,
                            ExpenseName = "Reembolso"
                        },
                        new
                        {
                            Id = 18,
                            ExpenseName = "Servicio de administración"
                        },
                        new
                        {
                            Id = 19,
                            ExpenseName = "Servicio de agua"
                        },
                        new
                        {
                            Id = 20,
                            ExpenseName = "Servicio de electricidad"
                        },
                        new
                        {
                            Id = 21,
                            ExpenseName = "Servicio de gas"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateValue = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            DateValue = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Martíres"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentName = "Cuota Ordinaria"
                        },
                        new
                        {
                            Id = 2,
                            PaymentName = "Cuota Extraordinaria"
                        },
                        new
                        {
                            Id = 3,
                            PaymentName = "Reserva de área común"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 911, DateTimeKind.Local).AddTicks(5662),
                            Email = "Jennifer61@yahoo.com",
                            Identification = "455 460 667",
                            Name = "Jennifer Cordero",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "544059567",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 911, DateTimeKind.Local).AddTicks(8148),
                            Email = "Esmeralda_Davila@yahoo.com",
                            Identification = "897 924 320",
                            Name = "Esmeralda Dávila",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "556233410",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 911, DateTimeKind.Local).AddTicks(9791),
                            Email = "Emily52@hotmail.com",
                            Identification = "847 306 396",
                            Name = "Emily Valverde",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5662-167-657",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 912, DateTimeKind.Local).AddTicks(1536),
                            Email = "Barbara_Estevez@hotmail.com",
                            Identification = "545 875 510",
                            Name = "Barbara Estévez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "545 250 055",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 912, DateTimeKind.Local).AddTicks(3171),
                            Email = "Marilu_Mejia84@yahoo.com",
                            Identification = "117 348 581",
                            Name = "Marilu Mejía",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "504 279 377",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 912, DateTimeKind.Local).AddTicks(4766),
                            Email = "Martin5@nearbpo.com",
                            Identification = "836 118 547",
                            Name = "Martín Domínguez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5007-995-894",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 912, DateTimeKind.Local).AddTicks(6290),
                            Email = "Blanca12@hotmail.com",
                            Identification = "661 240 960",
                            Name = "Blanca Pichardo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5472-648-731",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 912, DateTimeKind.Local).AddTicks(7884),
                            Email = "Armando_Cardenas28@yahoo.com",
                            Identification = "213 710 411",
                            Name = "Armando Cardenas",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "528536955",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 912, DateTimeKind.Local).AddTicks(9435),
                            Email = "Paulina15@gmail.com",
                            Identification = "302 781 612",
                            Name = "Paulina Kara",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "566049734",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(1068),
                            Email = "Gael.Meraz45@corpfolder.com",
                            Identification = "698 712 544",
                            Name = "Gael Meraz",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "512 554 828",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(2609),
                            Email = "Vanessa.Jimenez80@corpfolder.com",
                            Identification = "312 811 508",
                            Name = "Vanessa Jiménez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5717-322-418",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(4054),
                            Email = "Yamileth_Limon@gmail.com",
                            Identification = "345 921 142",
                            Name = "Yamileth Limón",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "590.851.652",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(5515),
                            Email = "Julia.Orozco31@yahoo.com",
                            Identification = "240 137 513",
                            Name = "Julia Orozco",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5807-992-251",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(7008),
                            Email = "Lucas.Garcia32@hotmail.com",
                            Identification = "071 405 187",
                            Name = "Lucas García",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "569.445.507",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(8417),
                            Email = "Ignacio81@nearbpo.com",
                            Identification = "269 125 241",
                            Name = "Ignacio Zamora",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "552426948",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 913, DateTimeKind.Local).AddTicks(9932),
                            Email = "Roberto4@nearbpo.com",
                            Identification = "054 363 320",
                            Name = "Roberto Quintero de la cruz",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "580 150 431",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 914, DateTimeKind.Local).AddTicks(1451),
                            Email = "Berta_Brito@gmail.com",
                            Identification = "947 206 975",
                            Name = "Berta Brito",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5034-602-495",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 914, DateTimeKind.Local).AddTicks(3003),
                            Email = "Elizabeth9@hotmail.com",
                            Identification = "680 985 975",
                            Name = "Elizabeth Sanabria",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5815-123-675",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 914, DateTimeKind.Local).AddTicks(4478),
                            Email = "Jennifer91@nearbpo.com",
                            Identification = "968 013 045",
                            Name = "Jennifer Alva",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "527.626.755",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 914, DateTimeKind.Local).AddTicks(5893),
                            Email = "Armando34@yahoo.com",
                            Identification = "589 684 372",
                            Name = "Armando Gallardo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "592031256",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 914, DateTimeKind.Local).AddTicks(7364),
                            Email = "Patricio.Villanueva@gmail.com",
                            Identification = "299 269 506",
                            Name = "Patricio Villanueva",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "507082969",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 914, DateTimeKind.Local).AddTicks(8939),
                            Email = "Carlota_Padilla59@nearbpo.com",
                            Identification = "010 659 142",
                            Name = "Carlota Padilla",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "586 144 786",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(248),
                            Email = "Camila_Rico2@gmail.com",
                            Identification = "552 424 228",
                            Name = "Camila Rico",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "584962953",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(1623),
                            Email = "Manuel10@nearbpo.com",
                            Identification = "501 228 746",
                            Name = "Manuel Hinojosa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "550 637 592",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(3155),
                            Email = "Soledad_Verdugo@hotmail.com",
                            Identification = "907 497 119",
                            Name = "Soledad Verdugo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "567.693.679",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(4617),
                            Email = "Guillermina.Urbina77@nearbpo.com",
                            Identification = "669 893 331",
                            Name = "Guillermina Urbina",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "531.494.203",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(6083),
                            Email = "Ines.Kadarrodriguez@nearbpo.com",
                            Identification = "693 300 246",
                            Name = "Inés Kadar rodriguez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5308-656-609",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(7585),
                            Email = "Lorenzo35@nearbpo.com",
                            Identification = "338 246 994",
                            Name = "Lorenzo Sauceda",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5176-255-996",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 915, DateTimeKind.Local).AddTicks(9072),
                            Email = "Cristian.Cantu36@gmail.com",
                            Identification = "758 719 728",
                            Name = "Cristian Cantú",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "569 323 908",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 916, DateTimeKind.Local).AddTicks(610),
                            Email = "Hugo24@corpfolder.com",
                            Identification = "525 039 970",
                            Name = "Hugo Orozco",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5908-473-471",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 916, DateTimeKind.Local).AddTicks(2045),
                            Email = "Jose.Ojeda27@nearbpo.com",
                            Identification = "365 930 817",
                            Name = "José Ojeda",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "550 933 557",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 916, DateTimeKind.Local).AddTicks(3561),
                            Email = "Arturo_Nino@nearbpo.com",
                            Identification = "018 080 564",
                            Name = "Arturo Niño",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5651-444-657",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 916, DateTimeKind.Local).AddTicks(5061),
                            Email = "JoseAntonio44@corpfolder.com",
                            Identification = "073 302 754",
                            Name = "José Antonio Espinosa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "570783868",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 916, DateTimeKind.Local).AddTicks(7221),
                            Email = "Joaquin_Hinojosa@yahoo.com",
                            Identification = "873 937 486",
                            Name = "Joaquín Hinojosa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "510621873",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 916, DateTimeKind.Local).AddTicks(8823),
                            Email = "Adriana.Arenas61@corpfolder.com",
                            Identification = "293 485 009",
                            Name = "Adriana Arenas",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5126-085-172",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(305),
                            Email = "Daniel_Heredia28@hotmail.com",
                            Identification = "538 705 898",
                            Name = "Daniel Heredia",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5813-422-709",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(1801),
                            Email = "Marisol_Xana@nearbpo.com",
                            Identification = "674 834 346",
                            Name = "Marisol Xana",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "553 535 186",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(3300),
                            Email = "Mercedes7@corpfolder.com",
                            Identification = "001 895 119",
                            Name = "Mercedes Grijalva",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "559.782.876",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(4807),
                            Email = "Teresa_Dominguez@corpfolder.com",
                            Identification = "540 447 448",
                            Name = "Teresa Domínguez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "522 473 618",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(6273),
                            Email = "Eloisa.Karem94@corpfolder.com",
                            Identification = "353 630 569",
                            Name = "Eloisa Karem",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "566591341",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(7673),
                            Email = "Lola_Polanco75@yahoo.com",
                            Identification = "805 284 411",
                            Name = "Lola Polanco",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "522.157.173",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 917, DateTimeKind.Local).AddTicks(9078),
                            Email = "Gilberto_Rincon@yahoo.com",
                            Identification = "708 543 814",
                            Name = "Gilberto Rincón",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5561-128-461",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(628),
                            Email = "Maricarmen.Roldan64@gmail.com",
                            Identification = "651 133 381",
                            Name = "Maricarmen Roldán",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "553.831.802",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(2023),
                            Email = "Mateo_Maya24@nearbpo.com",
                            Identification = "621 133 180",
                            Name = "Mateo Maya",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "550.688.950",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(3480),
                            Email = "Alexa39@nearbpo.com",
                            Identification = "324 280 866",
                            Name = "Alexa Villareal",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "526.313.408",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(4898),
                            Email = "Melany.Olivarez84@nearbpo.com",
                            Identification = "975 919 911",
                            Name = "Melany Olivárez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5393-746-561",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(6325),
                            Email = "Esmeralda13@corpfolder.com",
                            Identification = "127 428 779",
                            Name = "Esmeralda Rincón",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "591 827 958",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(7872),
                            Email = "German95@yahoo.com",
                            Identification = "856 383 815",
                            Name = "Germán Jiménez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "564 716 505",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 918, DateTimeKind.Local).AddTicks(9442),
                            Email = "Emmanuel.Ledesma37@gmail.com",
                            Identification = "756 968 046",
                            Name = "Emmanuel Ledesma",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "528891399",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 919, DateTimeKind.Local).AddTicks(1045),
                            Email = "JuanPablo67@nearbpo.com",
                            Identification = "507 080 646",
                            Name = "Juan Pablo Zaragoza",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "549262570",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 919, DateTimeKind.Local).AddTicks(2600),
                            Email = "Jesus.Delgado49@hotmail.com",
                            Identification = "559 252 770",
                            Name = "Jesús Delgado",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "599753922",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 919, DateTimeKind.Local).AddTicks(4106),
                            Email = "Veronica28@hotmail.com",
                            Identification = "378 558 019",
                            Name = "Verónica Bahena",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5319-106-070",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 17, 9, 36, 48, 919, DateTimeKind.Local).AddTicks(5586),
                            Email = "Juana.Garibay78@gmail.com",
                            Identification = "641 605 894",
                            Name = "Juana Garibay",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5658-793-975",
                            RoleId = 2,
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHAdmin.API.Entities.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
