// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    [Migration("20221206142511_uno")]
    partial class uno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(666),
                            Floor = 1,
                            Letter = "A",
                            Name = "1-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(688),
                            Floor = 1,
                            Letter = "B",
                            Name = "1-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(689),
                            Floor = 1,
                            Letter = "C",
                            Name = "1-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(690),
                            Floor = 2,
                            Letter = "A",
                            Name = "2-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(692),
                            Floor = 2,
                            Letter = "B",
                            Name = "2-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(693),
                            Floor = 2,
                            Letter = "C",
                            Name = "2-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(694),
                            Floor = 2,
                            Letter = "D",
                            Name = "2-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(696),
                            Floor = 2,
                            Letter = "E",
                            Name = "2-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(697),
                            Floor = 3,
                            Letter = "A",
                            Name = "3-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(698),
                            Floor = 3,
                            Letter = "B",
                            Name = "3-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(699),
                            Floor = 3,
                            Letter = "C",
                            Name = "3-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(700),
                            Floor = 3,
                            Letter = "D",
                            Name = "3-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 996, DateTimeKind.Local).AddTicks(702),
                            Floor = 3,
                            Letter = "E",
                            Name = "3-E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateValue = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            DateValue = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Martíres"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentName = "Cuota Ordinaria"
                        },
                        new
                        {
                            Id = 2,
                            PaymentName = "Cuota Extraordinaria"
                        },
                        new
                        {
                            Id = 3,
                            PaymentName = "Reserva de área común"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(2497),
                            Email = "Paulina.Korta@hotmail.com",
                            Identification = "393 711 122",
                            Name = "Paulina Korta",
                            Password = "1234",
                            Phone = "549.670.810",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(3526),
                            Email = "Hugo75@nearbpo.com",
                            Identification = "170 248 900",
                            Name = "Hugo Rodarte",
                            Password = "1234",
                            Phone = "5773-486-850",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(4167),
                            Email = "AnaSofia26@yahoo.com",
                            Identification = "067 285 411",
                            Name = "Ana Sofía Ibarra",
                            Password = "1234",
                            Phone = "5874-931-526",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(4803),
                            Email = "Alexa_Espinal@corpfolder.com",
                            Identification = "908 452 576",
                            Name = "Alexa Espinal",
                            Password = "1234",
                            Phone = "549 616 446",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(5402),
                            Email = "Dolores_Maya91@gmail.com",
                            Identification = "645 214 552",
                            Name = "Dolores Maya",
                            Password = "1234",
                            Phone = "5744-647-086",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(5996),
                            Email = "Lorena.Kanaria20@gmail.com",
                            Identification = "280 475 054",
                            Name = "Lorena Kanaria",
                            Password = "1234",
                            Phone = "515319241",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(6624),
                            Email = "AngelGabriel99@yahoo.com",
                            Identification = "077 337 962",
                            Name = "Ángel Gabriel Peralta",
                            Password = "1234",
                            Phone = "599 341 869",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(7267),
                            Email = "Nicole8@yahoo.com",
                            Identification = "201 586 120",
                            Name = "Nicole Gaitán",
                            Password = "1234",
                            Phone = "513.620.421",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(7881),
                            Email = "Natalia.Espinal@corpfolder.com",
                            Identification = "863 240 453",
                            Name = "Natalia Espinal",
                            Password = "1234",
                            Phone = "545142498",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(8461),
                            Email = "LuisFernando76@gmail.com",
                            Identification = "184 012 169",
                            Name = "Luis Fernando Verdugo",
                            Password = "1234",
                            Phone = "5692-296-824",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(9065),
                            Email = "Israel.Briones88@hotmail.com",
                            Identification = "153 595 889",
                            Name = "Israel Briones",
                            Password = "1234",
                            Phone = "5934-355-899",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 998, DateTimeKind.Local).AddTicks(9629),
                            Email = "Rafael_Pantoja@yahoo.com",
                            Identification = "574 073 532",
                            Name = "Rafael Pantoja",
                            Password = "1234",
                            Phone = "522.032.834",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(247),
                            Email = "AngelGabriel73@hotmail.com",
                            Identification = "499 399 517",
                            Name = "Ángel Gabriel Gallegos",
                            Password = "1234",
                            Phone = "526398360",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(891),
                            Email = "Emiliano.Sedillo4@gmail.com",
                            Identification = "709 991 921",
                            Name = "Emiliano Sedillo",
                            Password = "1234",
                            Phone = "557.940.851",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(1514),
                            Email = "Martin.Segovia@yahoo.com",
                            Identification = "198 404 782",
                            Name = "Martín Segovia",
                            Password = "1234",
                            Phone = "561.419.772",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(2078),
                            Email = "Mayte.Pelayo90@gmail.com",
                            Identification = "842 066 656",
                            Name = "Mayte Pelayo",
                            Password = "1234",
                            Phone = "561.896.509",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(2707),
                            Email = "Uriel_Rios@gmail.com",
                            Identification = "575 905 062",
                            Name = "Uriel Ríos",
                            Password = "1234",
                            Phone = "589 671 770",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(3312),
                            Email = "Jorge21@hotmail.com",
                            Identification = "619 684 046",
                            Name = "Jorge Saldivar",
                            Password = "1234",
                            Phone = "581912058",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(3870),
                            Email = "Eloisa_Madrigal@nearbpo.com",
                            Identification = "561 193 442",
                            Name = "Eloisa Madrigal",
                            Password = "1234",
                            Phone = "5005-431-835",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(4516),
                            Email = "Lucas64@nearbpo.com",
                            Identification = "124 082 215",
                            Name = "Lucas Alonzo",
                            Password = "1234",
                            Phone = "500 731 980",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(5069),
                            Email = "Jacobo.Luevano@nearbpo.com",
                            Identification = "541 197 141",
                            Name = "Jacobo Luevano",
                            Password = "1234",
                            Phone = "526.640.000",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(5647),
                            Email = "Emiliano_Collado@yahoo.com",
                            Identification = "275 430 148",
                            Name = "Emiliano Collado",
                            Password = "1234",
                            Phone = "5568-786-240",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(6230),
                            Email = "Paola_Jaime@nearbpo.com",
                            Identification = "013 483 326",
                            Name = "Paola Jaime",
                            Password = "1234",
                            Phone = "509.767.098",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(6803),
                            Email = "Sancho66@gmail.com",
                            Identification = "207 300 468",
                            Name = "Sancho Ortiz",
                            Password = "1234",
                            Phone = "533467317",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(7389),
                            Email = "Ricardo_Tello@nearbpo.com",
                            Identification = "180 403 248",
                            Name = "Ricardo Tello",
                            Password = "1234",
                            Phone = "524978221",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(8136),
                            Email = "Marisol.Montenegro21@yahoo.com",
                            Identification = "279 660 690",
                            Name = "Marisol Montenegro",
                            Password = "1234",
                            Phone = "5460-398-158",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(8749),
                            Email = "Lucas_Navarrete@yahoo.com",
                            Identification = "832 220 081",
                            Name = "Lucas Navarrete",
                            Password = "1234",
                            Phone = "543866174",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(9297),
                            Email = "Teodoro_Trejo@hotmail.com",
                            Identification = "524 980 190",
                            Name = "Teodoro Trejo",
                            Password = "1234",
                            Phone = "5499-671-662",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 10, 999, DateTimeKind.Local).AddTicks(9874),
                            Email = "Ernesto_Vargas@gmail.com",
                            Identification = "313 250 797",
                            Name = "Ernesto Vargas",
                            Password = "1234",
                            Phone = "587 128 467",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(554),
                            Email = "Fatima18@corpfolder.com",
                            Identification = "241 831 882",
                            Name = "Fatima Arellano",
                            Password = "1234",
                            Phone = "528023606",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(1152),
                            Email = "Alfonso.Murillo11@gmail.com",
                            Identification = "905 288 254",
                            Name = "Alfonso Murillo",
                            Password = "1234",
                            Phone = "583938092",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(1725),
                            Email = "Roberto73@hotmail.com",
                            Identification = "267 674 679",
                            Name = "Roberto Rojas",
                            Password = "1234",
                            Phone = "557 474 340",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(2350),
                            Email = "Salvador_Gastelum@nearbpo.com",
                            Identification = "849 427 752",
                            Name = "Salvador Gastélum",
                            Password = "1234",
                            Phone = "546 662 377",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(3010),
                            Email = "Patricio.Vargas3@corpfolder.com",
                            Identification = "542 259 676",
                            Name = "Patricio Vargas",
                            Password = "1234",
                            Phone = "595 903 195",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(3611),
                            Email = "Luz97@gmail.com",
                            Identification = "370 401 606",
                            Name = "Luz Palomo",
                            Password = "1234",
                            Phone = "5486-002-529",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(4236),
                            Email = "Luisa43@yahoo.com",
                            Identification = "815 435 367",
                            Name = "Luisa Armendáriz",
                            Password = "1234",
                            Phone = "584158865",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(4856),
                            Email = "Francisca.Posada@hotmail.com",
                            Identification = "823 025 119",
                            Name = "Francisca Posada",
                            Password = "1234",
                            Phone = "5765-769-427",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(5450),
                            Email = "MariaFernanda_Haro@gmail.com",
                            Identification = "411 627 706",
                            Name = "María Fernanda Haro",
                            Password = "1234",
                            Phone = "530906451",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(6018),
                            Email = "Guillermina15@yahoo.com",
                            Identification = "593 594 245",
                            Name = "Guillermina Iglesias",
                            Password = "1234",
                            Phone = "5279-164-445",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(6732),
                            Email = "Rosa.Velez71@yahoo.com",
                            Identification = "589 993 179",
                            Name = "Rosa Vélez",
                            Password = "1234",
                            Phone = "501 005 041",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(7315),
                            Email = "Lucas.Cavazos39@yahoo.com",
                            Identification = "066 807 868",
                            Name = "Lucas Cavazos",
                            Password = "1234",
                            Phone = "5273-011-427",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(7861),
                            Email = "Elena_Holguin10@gmail.com",
                            Identification = "149 413 254",
                            Name = "Elena Holguín",
                            Password = "1234",
                            Phone = "504983024",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(8491),
                            Email = "JoseMiguel_Sandoval91@nearbpo.com",
                            Identification = "441 534 567",
                            Name = "José Miguel Sandoval",
                            Password = "1234",
                            Phone = "517.764.727",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(9066),
                            Email = "Mateo94@gmail.com",
                            Identification = "215 898 735",
                            Name = "Mateo Rivero",
                            Password = "1234",
                            Phone = "564.459.716",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 0, DateTimeKind.Local).AddTicks(9624),
                            Email = "Arturo_Delarosa@nearbpo.com",
                            Identification = "220 624 043",
                            Name = "Arturo Delarosa",
                            Password = "1234",
                            Phone = "533 194 370",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(225),
                            Email = "Gael_Pulido@hotmail.com",
                            Identification = "127 512 796",
                            Name = "Gael Pulido",
                            Password = "1234",
                            Phone = "570 690 005",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(902),
                            Email = "Ximena26@yahoo.com",
                            Identification = "665 230 405",
                            Name = "Ximena Miranda",
                            Password = "1234",
                            Phone = "534.602.840",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(1460),
                            Email = "JoseMaria.Gollum@nearbpo.com",
                            Identification = "562 480 764",
                            Name = "José María Gollum",
                            Password = "1234",
                            Phone = "5035-581-918",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(2074),
                            Email = "Amalia_Urena4@yahoo.com",
                            Identification = "398 777 342",
                            Name = "Amalia Ureña",
                            Password = "1234",
                            Phone = "5604-925-675",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(2693),
                            Email = "Luis72@gmail.com",
                            Identification = "288 584 089",
                            Name = "Luis Gil",
                            Password = "1234",
                            Phone = "5778-436-169",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(3251),
                            Email = "Felipe.Ochoa@corpfolder.com",
                            Identification = "418 404 570",
                            Name = "Felipe Ochoa",
                            Password = "1234",
                            Phone = "517 199 084",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(3848),
                            Email = "Beatriz59@yahoo.com",
                            Identification = "930 579 529",
                            Name = "Beatriz Farías",
                            Password = "1234",
                            Phone = "5759-773-420",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 6, 9, 25, 11, 1, DateTimeKind.Local).AddTicks(4498),
                            Email = "Victor.Armenta71@corpfolder.com",
                            Identification = "450 460 068",
                            Name = "Víctor Armenta",
                            Password = "1234",
                            Phone = "5310-142-013",
                            RoleId = 2,
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHAdmin.API.Entities.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
