// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    [Migration("20221211231356_mig35")]
    partial class mig35
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6787),
                            Floor = 1,
                            Letter = "A",
                            Name = "1-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6812),
                            Floor = 1,
                            Letter = "B",
                            Name = "1-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6813),
                            Floor = 1,
                            Letter = "C",
                            Name = "1-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6815),
                            Floor = 2,
                            Letter = "A",
                            Name = "2-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6820),
                            Floor = 2,
                            Letter = "B",
                            Name = "2-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6821),
                            Floor = 2,
                            Letter = "C",
                            Name = "2-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6822),
                            Floor = 2,
                            Letter = "D",
                            Name = "2-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6826),
                            Floor = 2,
                            Letter = "E",
                            Name = "2-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6828),
                            Floor = 3,
                            Letter = "A",
                            Name = "3-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6829),
                            Floor = 3,
                            Letter = "B",
                            Name = "3-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6830),
                            Floor = 3,
                            Letter = "C",
                            Name = "3-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6831),
                            Floor = 3,
                            Letter = "D",
                            Name = "3-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6832),
                            Floor = 3,
                            Letter = "E",
                            Name = "3-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6863),
                            Floor = 4,
                            Letter = "A",
                            Name = "4-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6864),
                            Floor = 4,
                            Letter = "B",
                            Name = "4-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6865),
                            Floor = 4,
                            Letter = "C",
                            Name = "4-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6866),
                            Floor = 4,
                            Letter = "D",
                            Name = "4-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6870),
                            Floor = 4,
                            Letter = "E",
                            Name = "4-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6872),
                            Floor = 5,
                            Letter = "A",
                            Name = "5-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6873),
                            Floor = 5,
                            Letter = "B",
                            Name = "5-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6874),
                            Floor = 5,
                            Letter = "C",
                            Name = "5-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6875),
                            Floor = 5,
                            Letter = "D",
                            Name = "5-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6876),
                            Floor = 5,
                            Letter = "E",
                            Name = "5-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6877),
                            Floor = 6,
                            Letter = "A",
                            Name = "6-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6878),
                            Floor = 6,
                            Letter = "B",
                            Name = "6-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6879),
                            Floor = 6,
                            Letter = "C",
                            Name = "6-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6880),
                            Floor = 6,
                            Letter = "D",
                            Name = "6-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6881),
                            Floor = 6,
                            Letter = "E",
                            Name = "28-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6883),
                            Floor = 7,
                            Letter = "A",
                            Name = "7-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6884),
                            Floor = 7,
                            Letter = "B",
                            Name = "7-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6885),
                            Floor = 7,
                            Letter = "C",
                            Name = "7-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6886),
                            Floor = 7,
                            Letter = "D",
                            Name = "7-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6887),
                            Floor = 7,
                            Letter = "E",
                            Name = "33-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6889),
                            Floor = 8,
                            Letter = "A",
                            Name = "8-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6890),
                            Floor = 8,
                            Letter = "B",
                            Name = "8-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6891),
                            Floor = 8,
                            Letter = "C",
                            Name = "8-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6892),
                            Floor = 8,
                            Letter = "D",
                            Name = "8-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6893),
                            Floor = 8,
                            Letter = "E",
                            Name = "8-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6894),
                            Floor = 9,
                            Letter = "A",
                            Name = "9-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6895),
                            Floor = 9,
                            Letter = "B",
                            Name = "9-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6896),
                            Floor = 9,
                            Letter = "C",
                            Name = "9-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6898),
                            Floor = 9,
                            Letter = "D",
                            Name = "9-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6899),
                            Floor = 9,
                            Letter = "E",
                            Name = "9-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6900),
                            Floor = 10,
                            Letter = "A",
                            Name = "10-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6904),
                            Floor = 10,
                            Letter = "B",
                            Name = "10-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6905),
                            Floor = 10,
                            Letter = "C",
                            Name = "10-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6906),
                            Floor = 10,
                            Letter = "D",
                            Name = "10-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6907),
                            Floor = 10,
                            Letter = "E",
                            Name = "10-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6908),
                            Floor = 11,
                            Letter = "A",
                            Name = "11-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6909),
                            Floor = 11,
                            Letter = "B",
                            Name = "11-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6911),
                            Floor = 11,
                            Letter = "C",
                            Name = "11-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6912),
                            Floor = 11,
                            Letter = "D",
                            Name = "11-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 58, DateTimeKind.Local).AddTicks(6913),
                            Floor = 11,
                            Letter = "E",
                            Name = "11-E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<byte[]>("Document")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpenseName = "Artículos de limpieza"
                        },
                        new
                        {
                            Id = 2,
                            ExpenseName = "Caja de Seguro Social"
                        },
                        new
                        {
                            Id = 3,
                            ExpenseName = "Caja menuda"
                        },
                        new
                        {
                            Id = 4,
                            ExpenseName = "Cargos bancarios"
                        },
                        new
                        {
                            Id = 5,
                            ExpenseName = "Cerrajería"
                        },
                        new
                        {
                            Id = 6,
                            ExpenseName = "Conserje"
                        },
                        new
                        {
                            Id = 7,
                            ExpenseName = "Devolución de reserva"
                        },
                        new
                        {
                            Id = 8,
                            ExpenseName = "Fotocopias"
                        },
                        new
                        {
                            Id = 9,
                            ExpenseName = "Fumigación"
                        },
                        new
                        {
                            Id = 10,
                            ExpenseName = "Gastos legales"
                        },
                        new
                        {
                            Id = 11,
                            ExpenseName = "Mantenimiento de A/A."
                        },
                        new
                        {
                            Id = 12,
                            ExpenseName = "Mantenimiento de ascensores"
                        },
                        new
                        {
                            Id = 13,
                            ExpenseName = "Mantenimiento de bomba de agua"
                        },
                        new
                        {
                            Id = 14,
                            ExpenseName = "Mantenimiento de planta eléctrica"
                        },
                        new
                        {
                            Id = 15,
                            ExpenseName = "Mantenimiento de puertas mecánicas"
                        },
                        new
                        {
                            Id = 16,
                            ExpenseName = "Portería"
                        },
                        new
                        {
                            Id = 17,
                            ExpenseName = "Reembolso"
                        },
                        new
                        {
                            Id = 18,
                            ExpenseName = "Servicio de administración"
                        },
                        new
                        {
                            Id = 19,
                            ExpenseName = "Servicio de agua"
                        },
                        new
                        {
                            Id = 20,
                            ExpenseName = "Servicio de electricidad"
                        },
                        new
                        {
                            Id = 21,
                            ExpenseName = "Servicio de gas"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateValue = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            DateValue = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Martíres"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentName = "Cuota Ordinaria"
                        },
                        new
                        {
                            Id = 2,
                            PaymentName = "Cuota Extraordinaria"
                        },
                        new
                        {
                            Id = 3,
                            PaymentName = "Reserva de área común"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("A");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 64, DateTimeKind.Local).AddTicks(7316),
                            Email = "Roberto_Marin@hotmail.com",
                            Identification = "380 265 553",
                            Name = "Roberto Marín",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "547.058.514",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 64, DateTimeKind.Local).AddTicks(9581),
                            Email = "Rafael72@gmail.com",
                            Identification = "416 414 324",
                            Name = "Rafael Valle",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "507 180 448",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(645),
                            Email = "Antonia.Roque@yahoo.com",
                            Identification = "532 299 724",
                            Name = "Antonia Roque",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "517104893",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(2858),
                            Email = "Carolina94@gmail.com",
                            Identification = "390 318 301",
                            Name = "Carolina Barrios",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "507087274",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(4491),
                            Email = "Miranda.Lebron@yahoo.com",
                            Identification = "121 305 833",
                            Name = "Miranda Lebrón",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "535.880.910",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(5372),
                            Email = "Vanessa6@nearbpo.com",
                            Identification = "484 311 105",
                            Name = "Vanessa Flores",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5643-462-131",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(6294),
                            Email = "Cristobal.Caraballo0@yahoo.com",
                            Identification = "249 200 908",
                            Name = "Cristobal Caraballo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5507-933-760",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(7257),
                            Email = "Armando.Rico37@gmail.com",
                            Identification = "330 535 857",
                            Name = "Armando Rico",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "568762837",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 65, DateTimeKind.Local).AddTicks(9088),
                            Email = "Berta.Bonilla@gmail.com",
                            Identification = "964 994 115",
                            Name = "Berta Bonilla",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "548.312.139",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(353),
                            Email = "AnaMaria_Perez92@yahoo.com",
                            Identification = "064 927 593",
                            Name = "Ana María Pérez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "530646671",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(1489),
                            Email = "Andrea_Guzman@nearbpo.com",
                            Identification = "701 140 881",
                            Name = "Andrea Guzmán",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "506509230",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(2556),
                            Email = "Luz.Lucio@hotmail.com",
                            Identification = "639 257 245",
                            Name = "Luz Lucio",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "525104757",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(3538),
                            Email = "Sara.Pagan93@nearbpo.com",
                            Identification = "909 838 740",
                            Name = "Sara Pagan",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "508387201",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(5205),
                            Email = "Lilia.Villegas@nearbpo.com",
                            Identification = "040 981 102",
                            Name = "Lilia Villegas",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "581 692 295",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(6638),
                            Email = "Daniela_Villa@gmail.com",
                            Identification = "119 977 064",
                            Name = "Daniela Villa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "569 454 475",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(7818),
                            Email = "Eva.Zamora@gmail.com",
                            Identification = "842 453 169",
                            Name = "Eva Zamora",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "532.851.970",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(8839),
                            Email = "Luz.Garibay@nearbpo.com",
                            Identification = "871 611 455",
                            Name = "Luz Garibay",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "547 839 582",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 66, DateTimeKind.Local).AddTicks(9711),
                            Email = "Emilia.Orosco4@corpfolder.com",
                            Identification = "534 230 974",
                            Name = "Emilia Orosco",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "594.593.124",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(549),
                            Email = "AnaLuisa19@gmail.com",
                            Identification = "753 759 406",
                            Name = "Ana Luisa Chapa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "597587845",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(1280),
                            Email = "Natalia54@hotmail.com",
                            Identification = "541 430 609",
                            Name = "Natalia Alanis",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "506 550 231",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(2004),
                            Email = "Carolina_Garza@yahoo.com",
                            Identification = "913 722 070",
                            Name = "Carolina Garza",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "564 473 467",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(2720),
                            Email = "Sebastian67@yahoo.com",
                            Identification = "198 248 940",
                            Name = "Sebastian Soria",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "590.358.299",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(3380),
                            Email = "Hernan_Serrato57@nearbpo.com",
                            Identification = "291 346 708",
                            Name = "Hernán Serrato",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "570311438",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(4069),
                            Email = "Bernardo48@hotmail.com",
                            Identification = "246 360 796",
                            Name = "Bernardo Alvarez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5836-329-428",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(4771),
                            Email = "Elizabeth43@yahoo.com",
                            Identification = "551 798 473",
                            Name = "Elizabeth Venegas",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5294-026-135",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(5496),
                            Email = "Vicente_Hinojosa94@gmail.com",
                            Identification = "158 443 986",
                            Name = "Vicente Hinojosa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "505984070",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(6202),
                            Email = "Melany.Casas50@hotmail.com",
                            Identification = "017 456 799",
                            Name = "Melany Casas",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "509.738.684",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(6962),
                            Email = "Micaela_Solis@hotmail.com",
                            Identification = "363 675 687",
                            Name = "Micaela Solís",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "593.746.757",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(7791),
                            Email = "Renata_Hernandes32@hotmail.com",
                            Identification = "161 754 676",
                            Name = "Renata Hernandes",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5599-695-165",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(8514),
                            Email = "David.Olivo@hotmail.com",
                            Identification = "265 780 932",
                            Name = "David Olivo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "563867311",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(9259),
                            Email = "Eduardo_Escobar72@gmail.com",
                            Identification = "758 289 201",
                            Name = "Eduardo Escobar",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5790-341-358",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 67, DateTimeKind.Local).AddTicks(9936),
                            Email = "Adela_Duran74@gmail.com",
                            Identification = "467 864 260",
                            Name = "Adela Duran",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "573 973 968",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(678),
                            Email = "Federico.Segovia@corpfolder.com",
                            Identification = "580 767 564",
                            Name = "Federico Segovia",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "538.929.456",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(1387),
                            Email = "Claudia.Vega@hotmail.com",
                            Identification = "821 820 115",
                            Name = "Claudia Vega",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "516.344.037",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(2069),
                            Email = "Isabela_Iglesias@yahoo.com",
                            Identification = "542 974 704",
                            Name = "Isabela Iglesias",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "563 588 367",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(2721),
                            Email = "Irene.Rivero18@corpfolder.com",
                            Identification = "733 480 719",
                            Name = "Irene Rivero",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "579952249",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(3340),
                            Email = "Iker43@nearbpo.com",
                            Identification = "408 750 974",
                            Name = "Iker Mares",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "551543973",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(4061),
                            Email = "Bernardo_Gonzales0@hotmail.com",
                            Identification = "989 824 115",
                            Name = "Bernardo Gonzales",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "564 368 448",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(4739),
                            Email = "Esteban_Vazquez@corpfolder.com",
                            Identification = "429 479 892",
                            Name = "Esteban Vázquez",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5912-204-818",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(5434),
                            Email = "Diego_Espinosa66@hotmail.com",
                            Identification = "993 242 684",
                            Name = "Diego Espinosa",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "538.457.492",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(6220),
                            Email = "Emily.Samaniego@corpfolder.com",
                            Identification = "329 455 679",
                            Name = "Emily Samaniego",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "528378071",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(7088),
                            Email = "AnaMaria.Archuleta@hotmail.com",
                            Identification = "636 468 647",
                            Name = "Ana María Archuleta",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "588 693 477",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(8081),
                            Email = "Yolanda74@nearbpo.com",
                            Identification = "111 971 347",
                            Name = "Yolanda Villarreal",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "568 457 257",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(8893),
                            Email = "Rosario.Vargas@corpfolder.com",
                            Identification = "512 021 890",
                            Name = "Rosario Vargas",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "503.126.368",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 68, DateTimeKind.Local).AddTicks(9677),
                            Email = "MariadeJesus_Mateo@gmail.com",
                            Identification = "176 979 771",
                            Name = "María de Jesús Mateo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5735-358-700",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(495),
                            Email = "Emilio_Ocampo34@hotmail.com",
                            Identification = "246 778 500",
                            Name = "Emilio Ocampo",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5911-304-250",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(1352),
                            Email = "Luisa_Aranda@nearbpo.com",
                            Identification = "761 189 901",
                            Name = "Luisa Aranda",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "589653502",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(2093),
                            Email = "JoseEmilio.Arriaga78@corpfolder.com",
                            Identification = "999 235 708",
                            Name = "José Emilio Arriaga",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "593 350 697",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(2760),
                            Email = "Lucas.Barraza95@corpfolder.com",
                            Identification = "909 828 378",
                            Name = "Lucas Barraza",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "564 898 611",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(3443),
                            Email = "Mariana.Urena23@gmail.com",
                            Identification = "977 786 235",
                            Name = "Mariana Ureña",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5567-249-279",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(5169),
                            Email = "Diana.Campos@corpfolder.com",
                            Identification = "369 894 522",
                            Name = "Diana Campos",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "556 715 643",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(6761),
                            Email = "Felipe_Munoz@gmail.com",
                            Identification = "579 576 497",
                            Name = "Felipe Muñoz",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5063-160-600",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 11, 18, 13, 56, 69, DateTimeKind.Local).AddTicks(7607),
                            Email = "Rodrigo.Rincon@gmail.com",
                            Identification = "265 570 531",
                            Name = "Rodrigo Rincón",
                            Password = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "5832-617-807",
                            RoleId = 2,
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHAdmin.API.Entities.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
