// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    [Migration("20221123153048_New7")]
    partial class New7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9596),
                            Floor = 1,
                            Letter = "A",
                            Name = "1-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9620),
                            Floor = 1,
                            Letter = "B",
                            Name = "1-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9621),
                            Floor = 1,
                            Letter = "C",
                            Name = "1-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9622),
                            Floor = 2,
                            Letter = "A",
                            Name = "2-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9623),
                            Floor = 2,
                            Letter = "B",
                            Name = "2-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9625),
                            Floor = 2,
                            Letter = "C",
                            Name = "2-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9627),
                            Floor = 2,
                            Letter = "D",
                            Name = "2-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9629),
                            Floor = 2,
                            Letter = "E",
                            Name = "2-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9630),
                            Floor = 3,
                            Letter = "A",
                            Name = "3-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9631),
                            Floor = 3,
                            Letter = "B",
                            Name = "3-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9632),
                            Floor = 3,
                            Letter = "C",
                            Name = "3-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9632),
                            Floor = 3,
                            Letter = "D",
                            Name = "3-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 675, DateTimeKind.Local).AddTicks(9634),
                            Floor = 3,
                            Letter = "E",
                            Name = "3-E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpenseName = "Agua"
                        },
                        new
                        {
                            Id = 2,
                            ExpenseName = "Luz"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateValue = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            DateValue = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Martíres"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentName = "Cuota Ordinaria"
                        },
                        new
                        {
                            Id = 2,
                            PaymentName = "Cuota Extraordinaria"
                        },
                        new
                        {
                            Id = 3,
                            PaymentName = "Reserva de área común"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 679, DateTimeKind.Local).AddTicks(598),
                            Email = "Ernesto_Kortahernandez68@nearbpo.com",
                            Identification = "950 010 611",
                            Name = "Ernesto Korta hernandez",
                            Password = "1234",
                            Phone = "5475-290-045",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 679, DateTimeKind.Local).AddTicks(1722),
                            Email = "Clara19@hotmail.com",
                            Identification = "277 297 610",
                            Name = "Clara Rico",
                            Password = "1234",
                            Phone = "5212-875-635",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 679, DateTimeKind.Local).AddTicks(3284),
                            Email = "Rodrigo.Armenta@gmail.com",
                            Identification = "220 603 799",
                            Name = "Rodrigo Armenta",
                            Password = "1234",
                            Phone = "561 419 266",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 679, DateTimeKind.Local).AddTicks(4502),
                            Email = "Xochitl_Barragan29@nearbpo.com",
                            Identification = "310 436 829",
                            Name = "Xochitl Barragán",
                            Password = "1234",
                            Phone = "5743-690-681",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 679, DateTimeKind.Local).AddTicks(7542),
                            Email = "JoseMiguel_Galvan56@hotmail.com",
                            Identification = "759 763 154",
                            Name = "José Miguel Galván",
                            Password = "1234",
                            Phone = "558674507",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 679, DateTimeKind.Local).AddTicks(9780),
                            Email = "JoseAntonio28@gmail.com",
                            Identification = "197 452 543",
                            Name = "José Antonio Huerta",
                            Password = "1234",
                            Phone = "569 578 628",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 680, DateTimeKind.Local).AddTicks(1586),
                            Email = "Micaela.Galvan@gmail.com",
                            Identification = "611 919 481",
                            Name = "Micaela Galván",
                            Password = "1234",
                            Phone = "574597869",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 680, DateTimeKind.Local).AddTicks(3340),
                            Email = "JoseMiguel_Trujillo@hotmail.com",
                            Identification = "403 764 178",
                            Name = "José Miguel Trujillo",
                            Password = "1234",
                            Phone = "515 157 581",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 680, DateTimeKind.Local).AddTicks(5325),
                            Email = "Elsa_Zambrano@gmail.com",
                            Identification = "157 373 283",
                            Name = "Elsa Zambrano",
                            Password = "1234",
                            Phone = "530.275.100",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 680, DateTimeKind.Local).AddTicks(7360),
                            Email = "Valeria.Paredes56@nearbpo.com",
                            Identification = "499 142 867",
                            Name = "Valeria Paredes",
                            Password = "1234",
                            Phone = "521434082",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 680, DateTimeKind.Local).AddTicks(9287),
                            Email = "Irene15@hotmail.com",
                            Identification = "790 779 813",
                            Name = "Irene Gallegos",
                            Password = "1234",
                            Phone = "5404-011-006",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(429),
                            Email = "Andres_Razo@gmail.com",
                            Identification = "106 886 617",
                            Name = "Andrés Razo",
                            Password = "1234",
                            Phone = "529.179.377",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(1596),
                            Email = "Elizabeth.Salas40@yahoo.com",
                            Identification = "007 136 997",
                            Name = "Elizabeth Salas",
                            Password = "1234",
                            Phone = "537 929 545",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(3645),
                            Email = "AlondraRomina20@gmail.com",
                            Identification = "296 923 808",
                            Name = "Alondra Romina Calvillo",
                            Password = "1234",
                            Phone = "5670-936-558",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(5215),
                            Email = "MariaGuadalupe83@corpfolder.com",
                            Identification = "311 522 981",
                            Name = "María Guadalupe Calvillo",
                            Password = "1234",
                            Phone = "515 557 394",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(7071),
                            Email = "Martin57@gmail.com",
                            Identification = "271 305 658",
                            Name = "Martín Carbajal",
                            Password = "1234",
                            Phone = "5345-422-103",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(8348),
                            Email = "Agustin_Pineda@gmail.com",
                            Identification = "635 803 257",
                            Name = "Agustín Pineda",
                            Password = "1234",
                            Phone = "5593-120-904",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 681, DateTimeKind.Local).AddTicks(9907),
                            Email = "JoseMaria.Zamarripa@gmail.com",
                            Identification = "394 644 769",
                            Name = "José María Zamarripa",
                            Password = "1234",
                            Phone = "5957-915-668",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(714),
                            Email = "JuanManuel_Kyra@gmail.com",
                            Identification = "846 556 330",
                            Name = "Juan Manuel Kyra",
                            Password = "1234",
                            Phone = "5119-003-019",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(1411),
                            Email = "Jeronimo68@gmail.com",
                            Identification = "399 463 496",
                            Name = "Jerónimo Aguayo",
                            Password = "1234",
                            Phone = "533 533 172",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(2086),
                            Email = "Cristobal6@corpfolder.com",
                            Identification = "563 693 076",
                            Name = "Cristobal Gonzales",
                            Password = "1234",
                            Phone = "551 807 570",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(2848),
                            Email = "Paulina.Ocampo@hotmail.com",
                            Identification = "706 936 853",
                            Name = "Paulina Ocampo",
                            Password = "1234",
                            Phone = "5412-813-216",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(3572),
                            Email = "Andres.Arenas@yahoo.com",
                            Identification = "316 922 574",
                            Name = "Andrés Arenas",
                            Password = "1234",
                            Phone = "525 190 083",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(4317),
                            Email = "Carmen48@nearbpo.com",
                            Identification = "885 494 955",
                            Name = "Carmen Collado",
                            Password = "1234",
                            Phone = "5504-462-799",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(5100),
                            Email = "Eloisa64@gmail.com",
                            Identification = "043 897 743",
                            Name = "Eloisa Karen",
                            Password = "1234",
                            Phone = "5288-441-824",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(5695),
                            Email = "Luis_Tapia@corpfolder.com",
                            Identification = "478 737 117",
                            Name = "Luis Tapia",
                            Password = "1234",
                            Phone = "545 669 344",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(6301),
                            Email = "Maria.Tejeda64@hotmail.com",
                            Identification = "690 060 819",
                            Name = "María Tejeda",
                            Password = "1234",
                            Phone = "562.342.082",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(6887),
                            Email = "Enrique_Nava@yahoo.com",
                            Identification = "269 037 750",
                            Name = "Enrique Nava",
                            Password = "1234",
                            Phone = "5416-287-909",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(7583),
                            Email = "JuanCarlos_Sanchez70@gmail.com",
                            Identification = "168 971 489",
                            Name = "Juan Carlos Sánchez",
                            Password = "1234",
                            Phone = "575.556.685",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(8244),
                            Email = "Marcela_Anaya41@gmail.com",
                            Identification = "793 879 396",
                            Name = "Marcela Anaya",
                            Password = "1234",
                            Phone = "558193948",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(8935),
                            Email = "JoseLuis23@yahoo.com",
                            Identification = "297 981 094",
                            Name = "José Luis Mateo",
                            Password = "1234",
                            Phone = "5307-969-375",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 682, DateTimeKind.Local).AddTicks(9559),
                            Email = "Manuel82@gmail.com",
                            Identification = "595 615 410",
                            Name = "Manuel Medina",
                            Password = "1234",
                            Phone = "5900-840-814",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(174),
                            Email = "AnaVictoria_Valenzuela@gmail.com",
                            Identification = "910 049 493",
                            Name = "Ana Victoria Valenzuela",
                            Password = "1234",
                            Phone = "5685-301-026",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(855),
                            Email = "Gonzalo23@gmail.com",
                            Identification = "713 033 421",
                            Name = "Gonzalo Kardache soto",
                            Password = "1234",
                            Phone = "5341-605-345",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(1535),
                            Email = "MariaGuadalupe85@corpfolder.com",
                            Identification = "485 756 696",
                            Name = "María Guadalupe Roldán",
                            Password = "1234",
                            Phone = "566444143",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(2167),
                            Email = "Teresa_Candelaria@gmail.com",
                            Identification = "979 387 362",
                            Name = "Teresa Candelaria",
                            Password = "1234",
                            Phone = "588049213",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(2850),
                            Email = "David.Alarcon84@hotmail.com",
                            Identification = "647 875 194",
                            Name = "David Alarcón",
                            Password = "1234",
                            Phone = "574.165.963",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(3502),
                            Email = "Lucas_Olivo@yahoo.com",
                            Identification = "548 048 784",
                            Name = "Lucas Olivo",
                            Password = "1234",
                            Phone = "5360-157-742",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(4111),
                            Email = "Emmanuel_Ortega@corpfolder.com",
                            Identification = "031 876 188",
                            Name = "Emmanuel Ortega",
                            Password = "1234",
                            Phone = "541.003.102",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(4758),
                            Email = "Isaac86@nearbpo.com",
                            Identification = "744 626 938",
                            Name = "Isaac Saldivar",
                            Password = "1234",
                            Phone = "556 677 247",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(5455),
                            Email = "Emilio.Trujillo71@yahoo.com",
                            Identification = "562 102 350",
                            Name = "Emilio Trujillo",
                            Password = "1234",
                            Phone = "552.767.965",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(6137),
                            Email = "RosaMaria_Varela@yahoo.com",
                            Identification = "590 206 611",
                            Name = "Rosa María Varela",
                            Password = "1234",
                            Phone = "511733058",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(6770),
                            Email = "Raul64@gmail.com",
                            Identification = "378 672 778",
                            Name = "Raúl Delatorre",
                            Password = "1234",
                            Phone = "5445-932-089",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(7531),
                            Email = "Daniela.Nino@hotmail.com",
                            Identification = "016 559 205",
                            Name = "Daniela Niño",
                            Password = "1234",
                            Phone = "5072-233-485",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(8385),
                            Email = "Alan.Campos@corpfolder.com",
                            Identification = "503 732 745",
                            Name = "Alan Campos",
                            Password = "1234",
                            Phone = "533466826",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(9158),
                            Email = "Lorena_Canales@hotmail.com",
                            Identification = "986 437 127",
                            Name = "Lorena Canales",
                            Password = "1234",
                            Phone = "568.968.883",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 683, DateTimeKind.Local).AddTicks(9933),
                            Email = "Alexa.Casanova16@corpfolder.com",
                            Identification = "143 542 470",
                            Name = "Alexa Casanova",
                            Password = "1234",
                            Phone = "501 105 902",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 684, DateTimeKind.Local).AddTicks(696),
                            Email = "Sancho.Laboy@gmail.com",
                            Identification = "569 687 015",
                            Name = "Sancho Laboy",
                            Password = "1234",
                            Phone = "503 340 865",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 684, DateTimeKind.Local).AddTicks(1354),
                            Email = "Claudio57@gmail.com",
                            Identification = "407 191 642",
                            Name = "Claudio Agosto",
                            Password = "1234",
                            Phone = "574 973 495",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 684, DateTimeKind.Local).AddTicks(2073),
                            Email = "Marisol_Quezada@hotmail.com",
                            Identification = "128 463 155",
                            Name = "Marisol Quezada",
                            Password = "1234",
                            Phone = "594375166",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 684, DateTimeKind.Local).AddTicks(2826),
                            Email = "Araceli.Mercado45@nearbpo.com",
                            Identification = "232 633 164",
                            Name = "Araceli Mercado",
                            Password = "1234",
                            Phone = "549 778 690",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 684, DateTimeKind.Local).AddTicks(3545),
                            Email = "Emilia.Armijo@hotmail.com",
                            Identification = "102 754 959",
                            Name = "Emilia Armijo",
                            Password = "1234",
                            Phone = "528 645 193",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 11, 23, 10, 30, 48, 684, DateTimeKind.Local).AddTicks(4235),
                            Email = "Olivia_Loera@hotmail.com",
                            Identification = "600 301 717",
                            Name = "Olivia Loera",
                            Password = "1234",
                            Phone = "5232-430-218",
                            RoleId = 2,
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
