// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    [Migration("20221122003634_tableRole2")]
    partial class tableRole2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9701),
                            Floor = 1,
                            Letter = "A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9713),
                            Floor = 1,
                            Letter = "B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9714),
                            Floor = 1,
                            Letter = "C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9715),
                            Floor = 2,
                            Letter = "A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9716),
                            Floor = 2,
                            Letter = "B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9716),
                            Floor = 2,
                            Letter = "C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9717),
                            Floor = 2,
                            Letter = "D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9718),
                            Floor = 2,
                            Letter = "E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9719),
                            Floor = 3,
                            Letter = "A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9720),
                            Floor = 3,
                            Letter = "B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9720),
                            Floor = 3,
                            Letter = "C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9721),
                            Floor = 3,
                            Letter = "D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 11, 21, 19, 36, 34, 776, DateTimeKind.Local).AddTicks(9721),
                            Floor = 3,
                            Letter = "E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
