// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    partial class PHAdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9252),
                            Floor = 1,
                            Letter = "A",
                            Name = "1-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9276),
                            Floor = 1,
                            Letter = "B",
                            Name = "1-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9277),
                            Floor = 1,
                            Letter = "C",
                            Name = "1-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9278),
                            Floor = 2,
                            Letter = "A",
                            Name = "2-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9280),
                            Floor = 2,
                            Letter = "B",
                            Name = "2-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9281),
                            Floor = 2,
                            Letter = "C",
                            Name = "2-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9282),
                            Floor = 2,
                            Letter = "D",
                            Name = "2-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9285),
                            Floor = 2,
                            Letter = "E",
                            Name = "2-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9289),
                            Floor = 3,
                            Letter = "A",
                            Name = "3-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9290),
                            Floor = 3,
                            Letter = "B",
                            Name = "3-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9292),
                            Floor = 3,
                            Letter = "C",
                            Name = "3-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9293),
                            Floor = 3,
                            Letter = "D",
                            Name = "3-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 625, DateTimeKind.Local).AddTicks(9294),
                            Floor = 3,
                            Letter = "E",
                            Name = "3-E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateValue = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            DateValue = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Martíres"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentName = "Cuota Ordinaria"
                        },
                        new
                        {
                            Id = 2,
                            PaymentName = "Cuota Extraordinaria"
                        },
                        new
                        {
                            Id = 3,
                            PaymentName = "Reserva de área común"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 628, DateTimeKind.Local).AddTicks(9079),
                            Email = "Brayan_Nanez@gmail.com",
                            Identification = "283 028 108",
                            Name = "Brayan Ñañez",
                            Password = "1234",
                            Phone = "584841386",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(469),
                            Email = "Maximiliano.Colon44@nearbpo.com",
                            Identification = "733 331 748",
                            Name = "Maximiliano Colón",
                            Password = "1234",
                            Phone = "530 157 857",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(1370),
                            Email = "Homero.Romo@yahoo.com",
                            Identification = "015 950 256",
                            Name = "Homero Romo",
                            Password = "1234",
                            Phone = "554689291",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(2259),
                            Email = "Emmanuel.Gonzalez51@gmail.com",
                            Identification = "583 532 759",
                            Name = "Emmanuel González",
                            Password = "1234",
                            Phone = "594 343 844",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(3279),
                            Email = "Rosalia84@gmail.com",
                            Identification = "226 537 942",
                            Name = "Rosalia Madrigal",
                            Password = "1234",
                            Phone = "500.048.658",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(4159),
                            Email = "Marisol.Yebra@yahoo.com",
                            Identification = "730 550 639",
                            Name = "Marisol Yebra",
                            Password = "1234",
                            Phone = "5908-714-003",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(4955),
                            Email = "Alexander_Nazario@nearbpo.com",
                            Identification = "027 675 669",
                            Name = "Alexander Nazario",
                            Password = "1234",
                            Phone = "514.505.007",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(5797),
                            Email = "Enrique_Contreras@hotmail.com",
                            Identification = "410 132 278",
                            Name = "Enrique Contreras",
                            Password = "1234",
                            Phone = "599.910.399",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(6570),
                            Email = "Cecilia55@nearbpo.com",
                            Identification = "928 362 300",
                            Name = "Cecilia Villa",
                            Password = "1234",
                            Phone = "579364550",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(7321),
                            Email = "Joaquin.Vargas@corpfolder.com",
                            Identification = "211 561 071",
                            Name = "Joaquín Vargas",
                            Password = "1234",
                            Phone = "599440197",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(8299),
                            Email = "Maximiliano_Montemayor34@gmail.com",
                            Identification = "703 549 477",
                            Name = "Maximiliano Montemayor",
                            Password = "1234",
                            Phone = "572.652.006",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(9163),
                            Email = "AnaVictoria.Kardachesoto18@corpfolder.com",
                            Identification = "996 616 892",
                            Name = "Ana Victoria Kardache soto",
                            Password = "1234",
                            Phone = "5550-741-473",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 629, DateTimeKind.Local).AddTicks(9943),
                            Email = "Gonzalo26@nearbpo.com",
                            Identification = "965 101 587",
                            Name = "Gonzalo Quevedo",
                            Password = "1234",
                            Phone = "556 529 773",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(720),
                            Email = "Uriel_Quinones@gmail.com",
                            Identification = "345 099 857",
                            Name = "Uriel Quiñones",
                            Password = "1234",
                            Phone = "513 302 073",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(1525),
                            Email = "Timoteo_Gaitan33@hotmail.com",
                            Identification = "830 367 041",
                            Name = "Timoteo Gaitán",
                            Password = "1234",
                            Phone = "536.146.009",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(2288),
                            Email = "Hugo.Gil@hotmail.com",
                            Identification = "765 996 566",
                            Name = "Hugo Gil",
                            Password = "1234",
                            Phone = "580 890 390",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(3153),
                            Email = "Timoteo.Lopez@hotmail.com",
                            Identification = "975 595 059",
                            Name = "Timoteo López",
                            Password = "1234",
                            Phone = "5160-513-640",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(3998),
                            Email = "Miguel_Quevedo65@gmail.com",
                            Identification = "558 098 240",
                            Name = "Miguel Quevedo",
                            Password = "1234",
                            Phone = "577 750 964",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(4736),
                            Email = "Marcela71@yahoo.com",
                            Identification = "560 083 636",
                            Name = "Marcela Franco",
                            Password = "1234",
                            Phone = "551 666 915",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(5494),
                            Email = "Adela_Portillo@corpfolder.com",
                            Identification = "095 208 757",
                            Name = "Adela Portillo",
                            Password = "1234",
                            Phone = "568654343",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(6227),
                            Email = "Marilu10@hotmail.com",
                            Identification = "246 013 726",
                            Name = "Marilu Arteaga",
                            Password = "1234",
                            Phone = "573179688",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(6986),
                            Email = "Horacio6@nearbpo.com",
                            Identification = "419 486 501",
                            Name = "Horacio Saldaña",
                            Password = "1234",
                            Phone = "520122963",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(7705),
                            Email = "Lourdes35@gmail.com",
                            Identification = "735 557 217",
                            Name = "Lourdes Limón",
                            Password = "1234",
                            Phone = "5707-727-371",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(8477),
                            Email = "Valentina_Estrada@corpfolder.com",
                            Identification = "708 632 237",
                            Name = "Valentina Estrada",
                            Password = "1234",
                            Phone = "5946-576-688",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 630, DateTimeKind.Local).AddTicks(9311),
                            Email = "Gilberto.Abreu@gmail.com",
                            Identification = "835 722 927",
                            Name = "Gilberto Abreu",
                            Password = "1234",
                            Phone = "5039-268-670",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(104),
                            Email = "MariaElena_Pagan78@hotmail.com",
                            Identification = "920 130 705",
                            Name = "María Elena Pagan",
                            Password = "1234",
                            Phone = "521.638.529",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(945),
                            Email = "Emmanuel.Urena@gmail.com",
                            Identification = "023 320 104",
                            Name = "Emmanuel Ureña",
                            Password = "1234",
                            Phone = "5069-404-288",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(1706),
                            Email = "Rosalia32@corpfolder.com",
                            Identification = "688 711 506",
                            Name = "Rosalia Leal",
                            Password = "1234",
                            Phone = "584.237.147",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(2447),
                            Email = "Conchita_Cintron6@gmail.com",
                            Identification = "956 961 486",
                            Name = "Conchita Cintrón",
                            Password = "1234",
                            Phone = "590 193 444",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(3285),
                            Email = "Miranda_Miramontes@yahoo.com",
                            Identification = "782 480 792",
                            Name = "Miranda Miramontes",
                            Password = "1234",
                            Phone = "5150-266-494",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(4039),
                            Email = "Juana64@yahoo.com",
                            Identification = "884 346 925",
                            Name = "Juana Trejo",
                            Password = "1234",
                            Phone = "591701764",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(4865),
                            Email = "Marcela.Mascarenas@yahoo.com",
                            Identification = "036 962 512",
                            Name = "Marcela Mascareñas",
                            Password = "1234",
                            Phone = "527 832 934",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(5644),
                            Email = "Lola34@corpfolder.com",
                            Identification = "754 195 378",
                            Name = "Lola Montoya",
                            Password = "1234",
                            Phone = "529515712",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(6457),
                            Email = "Cecilia_Quinta29@gmail.com",
                            Identification = "123 182 370",
                            Name = "Cecilia Quinta",
                            Password = "1234",
                            Phone = "5971-907-874",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(7366),
                            Email = "Carlos23@yahoo.com",
                            Identification = "639 082 882",
                            Name = "Carlos Jimínez",
                            Password = "1234",
                            Phone = "508829572",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(8184),
                            Email = "Regina.Guajardo@yahoo.com",
                            Identification = "345 393 540",
                            Name = "Regina Guajardo",
                            Password = "1234",
                            Phone = "511995009",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(8972),
                            Email = "Florencia29@nearbpo.com",
                            Identification = "694 759 291",
                            Name = "Florencia Madrigal",
                            Password = "1234",
                            Phone = "570.726.260",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 631, DateTimeKind.Local).AddTicks(9741),
                            Email = "Monica.Zamarreno@hotmail.com",
                            Identification = "905 019 105",
                            Name = "Mónica Zamarreno",
                            Password = "1234",
                            Phone = "536579450",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(576),
                            Email = "Carolina_Cardona80@yahoo.com",
                            Identification = "672 117 371",
                            Name = "Carolina Cardona",
                            Password = "1234",
                            Phone = "5647-227-623",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(1341),
                            Email = "Miguel61@nearbpo.com",
                            Identification = "292 287 034",
                            Name = "Miguel Ceballos",
                            Password = "1234",
                            Phone = "517 812 188",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(2093),
                            Email = "JuanPablo.Arroyo@hotmail.com",
                            Identification = "291 454 106",
                            Name = "Juan Pablo Arroyo",
                            Password = "1234",
                            Phone = "5576-458-733",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(2871),
                            Email = "Alejandra_Correa@hotmail.com",
                            Identification = "452 113 871",
                            Name = "Alejandra Correa",
                            Password = "1234",
                            Phone = "5919-831-711",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(3599),
                            Email = "Eloisa_Botello32@nearbpo.com",
                            Identification = "291 979 987",
                            Name = "Eloisa Botello",
                            Password = "1234",
                            Phone = "514236652",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(4498),
                            Email = "Ximena_Barrera@yahoo.com",
                            Identification = "769 939 018",
                            Name = "Ximena Barrera",
                            Password = "1234",
                            Phone = "527.547.626",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(5309),
                            Email = "Hugo.Farias@hotmail.com",
                            Identification = "367 819 174",
                            Name = "Hugo Farías",
                            Password = "1234",
                            Phone = "5954-556-807",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(6125),
                            Email = "Valeria_Valdez@gmail.com",
                            Identification = "801 835 182",
                            Name = "Valeria Valdez",
                            Password = "1234",
                            Phone = "5050-035-626",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(6867),
                            Email = "Julieta23@hotmail.com",
                            Identification = "299 455 618",
                            Name = "Julieta Rolón",
                            Password = "1234",
                            Phone = "512383960",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(7656),
                            Email = "FranciscoJavier_Arriaga@gmail.com",
                            Identification = "063 575 328",
                            Name = "Francisco Javier Arriaga",
                            Password = "1234",
                            Phone = "552342069",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(8571),
                            Email = "Carmen.Vasquez80@corpfolder.com",
                            Identification = "071 055 222",
                            Name = "Carmen Vásquez",
                            Password = "1234",
                            Phone = "509 880 223",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 632, DateTimeKind.Local).AddTicks(9870),
                            Email = "Nicole.Valentin24@corpfolder.com",
                            Identification = "522 490 655",
                            Name = "Nicole Valentín",
                            Password = "1234",
                            Phone = "567.364.522",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 633, DateTimeKind.Local).AddTicks(1648),
                            Email = "Silvia.Benitez93@nearbpo.com",
                            Identification = "817 942 022",
                            Name = "Silvia Benítez",
                            Password = "1234",
                            Phone = "546.854.471",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 633, DateTimeKind.Local).AddTicks(2852),
                            Email = "Emilio_Cordova@corpfolder.com",
                            Identification = "378 193 312",
                            Name = "Emilio Córdova",
                            Password = "1234",
                            Phone = "561 509 368",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 5, 20, 57, 26, 633, DateTimeKind.Local).AddTicks(3819),
                            Email = "Benito.Marquez27@gmail.com",
                            Identification = "681 605 853",
                            Name = "Benito Márquez",
                            Password = "1234",
                            Phone = "537448478",
                            RoleId = 2,
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHAdmin.API.Entities.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
