// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    partial class PHAdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8581),
                            Floor = 1,
                            Letter = "A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8592),
                            Floor = 1,
                            Letter = "B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8593),
                            Floor = 1,
                            Letter = "C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8594),
                            Floor = 2,
                            Letter = "A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8594),
                            Floor = 2,
                            Letter = "B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8595),
                            Floor = 2,
                            Letter = "C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8597),
                            Floor = 2,
                            Letter = "D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8598),
                            Floor = 2,
                            Letter = "E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8598),
                            Floor = 3,
                            Letter = "A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8599),
                            Floor = 3,
                            Letter = "B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8600),
                            Floor = 3,
                            Letter = "C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8600),
                            Floor = 3,
                            Letter = "D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 11, 21, 19, 22, 45, 967, DateTimeKind.Local).AddTicks(8601),
                            Floor = 3,
                            Letter = "E",
                            Status = "A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
