// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PHAdmin.API.DbContexts;

#nullable disable

namespace PHAdmin.API.Migrations
{
    [DbContext(typeof(PHAdminContext))]
    partial class PHAdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PHAdmin.API.Entities.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)")
                        .HasComputedColumnSql("CONVERT([varchar](2),[Floor]) + '-' + [Letter]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apartments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8031),
                            Floor = 1,
                            Letter = "A",
                            Name = "1-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8058),
                            Floor = 1,
                            Letter = "B",
                            Name = "1-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8059),
                            Floor = 1,
                            Letter = "C",
                            Name = "1-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8061),
                            Floor = 2,
                            Letter = "A",
                            Name = "2-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8062),
                            Floor = 2,
                            Letter = "B",
                            Name = "2-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8063),
                            Floor = 2,
                            Letter = "C",
                            Name = "2-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8065),
                            Floor = 2,
                            Letter = "D",
                            Name = "2-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8068),
                            Floor = 2,
                            Letter = "E",
                            Name = "2-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8070),
                            Floor = 3,
                            Letter = "A",
                            Name = "3-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8071),
                            Floor = 3,
                            Letter = "B",
                            Name = "3-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8072),
                            Floor = 3,
                            Letter = "C",
                            Name = "3-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8073),
                            Floor = 3,
                            Letter = "D",
                            Name = "3-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8075),
                            Floor = 3,
                            Letter = "E",
                            Name = "3-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8076),
                            Floor = 4,
                            Letter = "A",
                            Name = "4-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8077),
                            Floor = 4,
                            Letter = "B",
                            Name = "4-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8078),
                            Floor = 4,
                            Letter = "C",
                            Name = "4-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8080),
                            Floor = 4,
                            Letter = "D",
                            Name = "4-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8081),
                            Floor = 4,
                            Letter = "E",
                            Name = "4-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8083),
                            Floor = 5,
                            Letter = "A",
                            Name = "5-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8084),
                            Floor = 5,
                            Letter = "B",
                            Name = "5-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8085),
                            Floor = 5,
                            Letter = "C",
                            Name = "5-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8088),
                            Floor = 5,
                            Letter = "D",
                            Name = "5-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8089),
                            Floor = 5,
                            Letter = "E",
                            Name = "5-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8090),
                            Floor = 6,
                            Letter = "A",
                            Name = "6-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8092),
                            Floor = 6,
                            Letter = "B",
                            Name = "6-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8094),
                            Floor = 6,
                            Letter = "C",
                            Name = "6-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8095),
                            Floor = 6,
                            Letter = "D",
                            Name = "6-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8096),
                            Floor = 6,
                            Letter = "E",
                            Name = "28-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8097),
                            Floor = 7,
                            Letter = "A",
                            Name = "7-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8099),
                            Floor = 7,
                            Letter = "B",
                            Name = "7-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8100),
                            Floor = 7,
                            Letter = "C",
                            Name = "7-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8101),
                            Floor = 7,
                            Letter = "D",
                            Name = "7-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8102),
                            Floor = 7,
                            Letter = "E",
                            Name = "33-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8104),
                            Floor = 8,
                            Letter = "A",
                            Name = "8-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8106),
                            Floor = 8,
                            Letter = "B",
                            Name = "8-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8107),
                            Floor = 8,
                            Letter = "C",
                            Name = "8-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8108),
                            Floor = 8,
                            Letter = "D",
                            Name = "8-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8109),
                            Floor = 8,
                            Letter = "E",
                            Name = "8-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8110),
                            Floor = 9,
                            Letter = "A",
                            Name = "9-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8111),
                            Floor = 9,
                            Letter = "B",
                            Name = "9-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8113),
                            Floor = 9,
                            Letter = "C",
                            Name = "9-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8114),
                            Floor = 9,
                            Letter = "D",
                            Name = "9-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8115),
                            Floor = 9,
                            Letter = "E",
                            Name = "9-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8116),
                            Floor = 10,
                            Letter = "A",
                            Name = "10-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8117),
                            Floor = 10,
                            Letter = "B",
                            Name = "10-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8118),
                            Floor = 10,
                            Letter = "C",
                            Name = "10-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8120),
                            Floor = 10,
                            Letter = "D",
                            Name = "10-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8152),
                            Floor = 10,
                            Letter = "E",
                            Name = "10-E",
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8153),
                            Floor = 11,
                            Letter = "A",
                            Name = "11-A",
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8154),
                            Floor = 11,
                            Letter = "B",
                            Name = "11-B",
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8157),
                            Floor = 11,
                            Letter = "C",
                            Name = "11-C",
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8158),
                            Floor = 11,
                            Letter = "D",
                            Name = "11-D",
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 900, DateTimeKind.Local).AddTicks(8160),
                            Floor = 11,
                            Letter = "E",
                            Name = "11-E",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseTypeId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.ExpenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpenseName = "Artículos de limpieza"
                        },
                        new
                        {
                            Id = 2,
                            ExpenseName = "Caja de Seguro Social"
                        },
                        new
                        {
                            Id = 3,
                            ExpenseName = "Caja menuda"
                        },
                        new
                        {
                            Id = 4,
                            ExpenseName = "Cargos bancarios"
                        },
                        new
                        {
                            Id = 5,
                            ExpenseName = "Cerrajería"
                        },
                        new
                        {
                            Id = 6,
                            ExpenseName = "Conserje"
                        },
                        new
                        {
                            Id = 7,
                            ExpenseName = "Devolución de reserva"
                        },
                        new
                        {
                            Id = 8,
                            ExpenseName = "Fotocopias"
                        },
                        new
                        {
                            Id = 9,
                            ExpenseName = "Fumigación"
                        },
                        new
                        {
                            Id = 10,
                            ExpenseName = "Gastos legales"
                        },
                        new
                        {
                            Id = 11,
                            ExpenseName = "Mantenimiento de A/A."
                        },
                        new
                        {
                            Id = 12,
                            ExpenseName = "Mantenimiento de ascensores"
                        },
                        new
                        {
                            Id = 13,
                            ExpenseName = "Mantenimiento de bomba de agua"
                        },
                        new
                        {
                            Id = 14,
                            ExpenseName = "Mantenimiento de planta eléctrica"
                        },
                        new
                        {
                            Id = 15,
                            ExpenseName = "Mantenimiento de puertas mecánicas"
                        },
                        new
                        {
                            Id = 16,
                            ExpenseName = "Portería"
                        },
                        new
                        {
                            Id = 17,
                            ExpenseName = "Reembolso"
                        },
                        new
                        {
                            Id = 18,
                            ExpenseName = "Servicio de administración"
                        },
                        new
                        {
                            Id = 19,
                            ExpenseName = "Servicio de agua"
                        },
                        new
                        {
                            Id = 20,
                            ExpenseName = "Servicio de electricidad"
                        },
                        new
                        {
                            Id = 21,
                            ExpenseName = "Servicio de gas"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateValue = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Año Nuevo"
                        },
                        new
                        {
                            Id = 2,
                            DateValue = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Día de los Martíres"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentName = "Cuota Ordinaria"
                        },
                        new
                        {
                            Id = 2,
                            PaymentName = "Cuota Extraordinaria"
                        },
                        new
                        {
                            Id = 3,
                            PaymentName = "Reserva de área común"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Copropietario"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 903, DateTimeKind.Local).AddTicks(9683),
                            Email = "Blanca_Quezada53@gmail.com",
                            Identification = "824 898 449",
                            Name = "Blanca Quezada",
                            Password = "1234",
                            Phone = "5026-448-753",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(1211),
                            Email = "AngelGabriel66@hotmail.com",
                            Identification = "818 070 435",
                            Name = "Ángel Gabriel León",
                            Password = "1234",
                            Phone = "529 637 586",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(2289),
                            Email = "Armando_Casas@nearbpo.com",
                            Identification = "219 001 278",
                            Name = "Armando Casas",
                            Password = "1234",
                            Phone = "5660-014-629",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(3083),
                            Email = "Paola_Olivera@corpfolder.com",
                            Identification = "386 773 618",
                            Name = "Paola Olivera",
                            Password = "1234",
                            Phone = "5595-785-954",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(3947),
                            Email = "Susana.Kardachesoto@corpfolder.com",
                            Identification = "688 747 104",
                            Name = "Susana Kardache soto",
                            Password = "1234",
                            Phone = "599.447.551",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(4744),
                            Email = "Isabel92@nearbpo.com",
                            Identification = "390 411 411",
                            Name = "Isabel Sandoval",
                            Password = "1234",
                            Phone = "579.641.983",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(5763),
                            Email = "Isaias_Centeno69@gmail.com",
                            Identification = "358 810 687",
                            Name = "Isaias Centeno",
                            Password = "1234",
                            Phone = "578375061",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(6586),
                            Email = "Conchita66@corpfolder.com",
                            Identification = "446 858 979",
                            Name = "Conchita Gaona",
                            Password = "1234",
                            Phone = "571.496.079",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(7306),
                            Email = "Blanca_Orosco@yahoo.com",
                            Identification = "836 825 471",
                            Name = "Blanca Orosco",
                            Password = "1234",
                            Phone = "539.254.652",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(8108),
                            Email = "Leonardo_Nunez59@gmail.com",
                            Identification = "714 800 521",
                            Name = "Leonardo Núñez",
                            Password = "1234",
                            Phone = "541 240 249",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(8942),
                            Email = "FernandoJavier_Escalante@yahoo.com",
                            Identification = "021 255 955",
                            Name = "Fernando Javier Escalante",
                            Password = "1234",
                            Phone = "569424938",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 904, DateTimeKind.Local).AddTicks(9747),
                            Email = "Amalia_Fuentes@yahoo.com",
                            Identification = "475 627 949",
                            Name = "Amalia Fuentes",
                            Password = "1234",
                            Phone = "526 736 502",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(526),
                            Email = "Brayan.Rosario8@gmail.com",
                            Identification = "875 193 823",
                            Name = "Brayan Rosario",
                            Password = "1234",
                            Phone = "5243-922-479",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(1516),
                            Email = "Octavio2@corpfolder.com",
                            Identification = "927 824 797",
                            Name = "Octavio Escamilla",
                            Password = "1234",
                            Phone = "585 307 980",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(2419),
                            Email = "Angela_Rubio@nearbpo.com",
                            Identification = "144 533 742",
                            Name = "Ángela Rubio",
                            Password = "1234",
                            Phone = "512367606",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(3216),
                            Email = "Francisco31@corpfolder.com",
                            Identification = "844 493 270",
                            Name = "Francisco Urrutia",
                            Password = "1234",
                            Phone = "514.567.325",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(4040),
                            Email = "Isaias_Sotelo@yahoo.com",
                            Identification = "774 889 976",
                            Name = "Isaias Sotelo",
                            Password = "1234",
                            Phone = "543413811",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(4787),
                            Email = "MariadelCarmen.Navarrete@yahoo.com",
                            Identification = "581 218 450",
                            Name = "María del Carmen Navarrete",
                            Password = "1234",
                            Phone = "527 847 562",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(5521),
                            Email = "Marilu_Tamayo10@corpfolder.com",
                            Identification = "723 033 536",
                            Name = "Marilu Tamayo",
                            Password = "1234",
                            Phone = "5062-921-243",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(6379),
                            Email = "Nicole.Bustos9@corpfolder.com",
                            Identification = "982 919 185",
                            Name = "Nicole Bustos",
                            Password = "1234",
                            Phone = "505896818",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(7224),
                            Email = "Norma_Rascon@yahoo.com",
                            Identification = "513 834 101",
                            Name = "Norma Rascón",
                            Password = "1234",
                            Phone = "526200302",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(7918),
                            Email = "Gonzalo49@corpfolder.com",
                            Identification = "384 523 684",
                            Name = "Gonzalo Véliz",
                            Password = "1234",
                            Phone = "5172-822-390",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(8733),
                            Email = "Abril28@nearbpo.com",
                            Identification = "389 251 992",
                            Name = "Abril Mercado",
                            Password = "1234",
                            Phone = "5117-264-321",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 905, DateTimeKind.Local).AddTicks(9492),
                            Email = "Reina.Vallejo@yahoo.com",
                            Identification = "825 783 897",
                            Name = "Reina Vallejo",
                            Password = "1234",
                            Phone = "520.659.413",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(192),
                            Email = "Juana55@nearbpo.com",
                            Identification = "415 376 318",
                            Name = "Juana Rivero",
                            Password = "1234",
                            Phone = "544.766.403",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 26,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(932),
                            Email = "Esteban.Blanco46@yahoo.com",
                            Identification = "608 988 077",
                            Name = "Esteban Blanco",
                            Password = "1234",
                            Phone = "5513-312-709",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 27,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(1695),
                            Email = "MiguelAngel1@hotmail.com",
                            Identification = "046 104 055",
                            Name = "Miguel Ángel Rocha",
                            Password = "1234",
                            Phone = "572730347",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 28,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(2507),
                            Email = "LuisFernando_Zamarripa64@yahoo.com",
                            Identification = "251 801 478",
                            Name = "Luis Fernando Zamarripa",
                            Password = "1234",
                            Phone = "569008256",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 29,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(3269),
                            Email = "Esteban93@gmail.com",
                            Identification = "573 079 688",
                            Name = "Esteban Tafoya",
                            Password = "1234",
                            Phone = "554 664 230",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 30,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(4024),
                            Email = "Daniel16@gmail.com",
                            Identification = "578 856 387",
                            Name = "Daniel Centeno",
                            Password = "1234",
                            Phone = "561868281",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 31,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(4798),
                            Email = "Cecilia28@nearbpo.com",
                            Identification = "503 190 050",
                            Name = "Cecilia Campos",
                            Password = "1234",
                            Phone = "533.476.753",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 32,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(5524),
                            Email = "Olivia_Abrego34@gmail.com",
                            Identification = "626 186 415",
                            Name = "Olivia Abrego",
                            Password = "1234",
                            Phone = "581 900 106",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 33,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(6275),
                            Email = "Estefania.Dominquez80@gmail.com",
                            Identification = "547 953 117",
                            Name = "Estefanía Domínquez",
                            Password = "1234",
                            Phone = "559 409 326",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 34,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(6980),
                            Email = "Saul.Tamez77@corpfolder.com",
                            Identification = "234 625 804",
                            Name = "Saúl Tamez",
                            Password = "1234",
                            Phone = "550.412.124",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 35,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(7720),
                            Email = "Maria.Pabon@nearbpo.com",
                            Identification = "256 143 637",
                            Name = "María Pabón",
                            Password = "1234",
                            Phone = "505 488 456",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 36,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(8427),
                            Email = "Alan_Cardenas@corpfolder.com",
                            Identification = "327 297 834",
                            Name = "Alan Cardenas",
                            Password = "1234",
                            Phone = "554 210 256",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 37,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(9176),
                            Email = "Susana.Adorno37@nearbpo.com",
                            Identification = "799 839 436",
                            Name = "Susana Adorno",
                            Password = "1234",
                            Phone = "557.844.410",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 38,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 906, DateTimeKind.Local).AddTicks(9909),
                            Email = "Elisa_Alarcon81@nearbpo.com",
                            Identification = "469 313 787",
                            Name = "Elisa Alarcón",
                            Password = "1234",
                            Phone = "531319571",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 39,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(659),
                            Email = "Claudio_Holguin@nearbpo.com",
                            Identification = "338 609 126",
                            Name = "Claudio Holguín",
                            Password = "1234",
                            Phone = "524.317.922",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 40,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(1411),
                            Email = "Clara86@yahoo.com",
                            Identification = "297 135 766",
                            Name = "Clara Alfaro",
                            Password = "1234",
                            Phone = "571 008 749",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 41,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(2172),
                            Email = "JoseEduardo52@hotmail.com",
                            Identification = "170 565 584",
                            Name = "José Eduardo Rojas",
                            Password = "1234",
                            Phone = "500428596",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 42,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(2895),
                            Email = "Sara.Trujillo@gmail.com",
                            Identification = "347 878 217",
                            Name = "Sara Trujillo",
                            Password = "1234",
                            Phone = "575 400 440",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 43,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(3638),
                            Email = "Ricardo51@nearbpo.com",
                            Identification = "393 825 849",
                            Name = "Ricardo Valdivia",
                            Password = "1234",
                            Phone = "580 434 146",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 44,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(4344),
                            Email = "Enrique.Delapaz@corpfolder.com",
                            Identification = "311 679 732",
                            Name = "Enrique Delapaz",
                            Password = "1234",
                            Phone = "508.440.964",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 45,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(5103),
                            Email = "Beatriz.Longoria14@yahoo.com",
                            Identification = "508 928 215",
                            Name = "Beatriz Longoria",
                            Password = "1234",
                            Phone = "543 432 351",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 46,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(5860),
                            Email = "Conchita_Villalpando80@hotmail.com",
                            Identification = "753 389 212",
                            Name = "Conchita Villalpando",
                            Password = "1234",
                            Phone = "5665-589-728",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 47,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(6550),
                            Email = "Miranda.Chacon17@nearbpo.com",
                            Identification = "312 889 231",
                            Name = "Miranda Chacón",
                            Password = "1234",
                            Phone = "591599790",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 48,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(7280),
                            Email = "Anita88@yahoo.com",
                            Identification = "485 341 119",
                            Name = "Anita Caballero",
                            Password = "1234",
                            Phone = "5417-776-811",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 49,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(8033),
                            Email = "MariaJose_Arguello83@nearbpo.com",
                            Identification = "006 107 080",
                            Name = "María José Arguello",
                            Password = "1234",
                            Phone = "501.799.008",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 50,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(8735),
                            Email = "Esteban_Salas7@corpfolder.com",
                            Identification = "158 119 552",
                            Name = "Esteban Salas",
                            Password = "1234",
                            Phone = "562398854",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 51,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 907, DateTimeKind.Local).AddTicks(9486),
                            Email = "MariaTeresa.Galvan@yahoo.com",
                            Identification = "627 316 607",
                            Name = "María Teresa Galván",
                            Password = "1234",
                            Phone = "513386339",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 52,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 908, DateTimeKind.Local).AddTicks(217),
                            Email = "Santiago_Pineda11@hotmail.com",
                            Identification = "967 666 967",
                            Name = "Santiago Pineda",
                            Password = "1234",
                            Phone = "536.611.641",
                            RoleId = 2,
                            Status = "A"
                        },
                        new
                        {
                            Id = 53,
                            CreationDate = new DateTime(2022, 12, 6, 15, 22, 2, 908, DateTimeKind.Local).AddTicks(908),
                            Email = "Debora_Carmona@corpfolder.com",
                            Identification = "349 682 898",
                            Name = "Débora Carmona",
                            Password = "1234",
                            Phone = "510.370.668",
                            RoleId = 2,
                            Status = "A"
                        });
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Debt", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Apartment", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PHAdmin.API.Entities.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Expense", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.ExpenseType", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Payment", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.User", b =>
                {
                    b.HasOne("PHAdmin.API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PHAdmin.API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
